### Teste de Vida
GET http://localhost:3000/

###

### 1. Criar um novo usuário (Cadastro)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "jackson@email.com",
  "password": "minhasenha123"
}

###

### 2. Tentar criar o mesmo usuário (Deve dar erro 400)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "jackson@email.com",
  "password": "outrasenha456"
}

###

### 3. Fazer Login com sucesso
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "jackson@email.com",
  "password": "minhasenha123"
}

###

### 4. Fazer Login com senha errada (Deve dar erro 401)
POST http://localhost:3333/api/auth/login
Content-Type: application/json

{
  "email": "jackson@email.com",
  "password": "senhaerrada"
}

### 5. Tentar entrar na área VIP SEM o crachá (Deve dar erro 401)
GET http://localhost:3333/api/auth/perfil

###

### 6. Tentar entrar na área VIP COM o crachá
# ATENÇÃO: Cole o seu token gigantesco no lugar de "SEU_TOKEN_AQUI"
GET http://localhost:3333/api/auth/perfil
Authorization: Bearer 

### 7. Criar uma Nova Transação (Receita)
POST http://localhost:3333/api/transactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqYWNrc29uQGVtYWlsLmNvbSIsImlhdCI6MTc4OTMxMzc3NywiZXhwIjoxNzg5MzE3Mzc3fQ.Dp9cAj30Gu1oRPcA87n1DpdzDq9BPEpSz3wVXxOApvY

{
  "description": "Salário do Mês",
  "amount": 4500.00,
  "type": "income",
  "category": "Salário",
  "date": "2026-09-13"
}

###

### 8. Tentar Criar Despesa Negativa (O Service deve barrar!)
POST http://localhost:3333/api/transactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqYWNrc29uQGVtYWlsLmNvbSIsImlhdCI6MTc4OTMxMzc3NywiZXhwIjoxNzg5MzE3Mzc3fQ.Dp9cAj30Gu1oRPcA87n1DpdzDq9BPEpSz3wVXxOApvY

{
  "description": "Conta de Luz",
  "amount": -150.00,
  "type": "expense",
  "category": "Moradia",
  "date": "2026-09-15"
}

###

### 9. Listar minhas transações
GET http://localhost:3333/api/transactions

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqYWNrc29uQGVtYWlsLmNvbSIsImlhdCI6MTc4OTMxMzc3NywiZXhwIjoxNzg5MzE3Mzc3fQ.Dp9cAj30Gu1oRPcA87n1DpdzDq9BPEpSz3wVXxOApvY

### 10. Editar uma Transação Existente
# Troque a barra final pelo ID real da sua transação (ex: /api/transactions/1)
PUT http://localhost:3333/api/transactions/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqYWNrc29uQGVtYWlsLmNvbSIsImlhdCI6MTc4OTMxMzc3NywiZXhwIjoxNzg5MzE3Mzc3fQ.Dp9cAj30Gu1oRPcA87n1DpdzDq9BPEpSz3wVXxOApvY


{
  "description": "Salário do Mês (Com Bônus)",
  "amount": 5000.00,
  "type": "income",
  "category": "Salário",
  "date": "2026-09-13"
}

###

### 11. Deletar uma Transação
# Troque a barra final pelo ID real da transação que deseja apagar
DELETE http://localhost:3333/api/transactions/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqYWNrc29uQGVtYWlsLmNvbSIsImlhdCI6MTc4OTMxMzc3NywiZXhwIjoxNzg5MzE3Mzc3fQ.Dp9cAj30Gu1oRPcA87n1DpdzDq9BPEpSz3wVXxOApvY

### 12. Obter Resumo Financeiro (Dashboard)
GET http://localhost:3333/api/transactions/summary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqYWNrc29uQGVtYWlsLmNvbSIsImlhdCI6MTc4OTMxMzc3NywiZXhwIjoxNzg5MzE3Mzc3fQ.Dp9cAj30Gu1oRPcA87n1DpdzDq9BPEpSz3wVXxOApvY
